In [22]:
#EmrullahYarar_2021513064_16.04.2024_Lab6

In [3]:
import numpy as np

In [4]:
B = [[3.5, 0, -0.2], [0.15, -75.08, -4.3], [0, -0.2, 11.0]]
C = [[5.65], [1], [71.4]]
D1 = np.concatenate ((B, C), axis = 1)
print(D1)

[[  3.5    0.    -0.2    5.65]
 [  0.15 -75.08  -4.3    1.  ]
 [  0.    -0.2   11.    71.4 ]]


In [5]:
D = [[3.5, 0, -0.2], [0.15, -75.08, -4.3], [0, -0.2, 11.0]]
E = [[5.65, 1, 71.4]]
D2 = np.concatenate ((D, E), axis = 0)
print(D2)

[[  3.5    0.    -0.2 ]
 [  0.15 -75.08  -4.3 ]
 [  0.    -0.2   11.  ]
 [  5.65   1.    71.4 ]]


In [6]:
D = [[3.5, 0, -0.2], [0.15, -75.08, -4.3], [0, -0.2, 11.0]]
E = [[5.65, 1, 71.4]]
D3 = np.concatenate ((D, E), axis = None)
print(D3)

[  3.5    0.    -0.2    0.15 -75.08  -4.3    0.    -0.2   11.     5.65
   1.    71.4 ]


In [7]:
#A = coefficient matrix, it must be a square matrix
#b = right hand side vector
#x = solution error

def GaussNaive(A,b):
    A = np.matrix(A)
    b = np.matrix(b)
    m,n = A.shape

    if m != n:
        print('Matrix A should be square matrix')
        return

    Aug = np.concatenate((A,b), axis = 1)
    #print("Aug_1=,Aug)

#forward elimination
    for k in range (n):
        for i in range (k+1, n):
            factor = Aug[i,k] / Aug[k,k]
            Aug[i, k:] = Aug[i, k:] - factor * Aug[k, k:]
    print('U=', Aug)

#backward elimination
    x = np.zeros((n, 1))
    x[n-1] = Aug[n-1, n] / Aug[n-1, n-1]
    for i in range (n-1 , 1, -1):
        x[i] = (Aug[i, n] - np.dot(Aug[i, i+1:n], x[i+1:n])) / Aug[i, i]
    print("x=", Aug[:, -1])
            

In [8]:
A = [[3, -0.1, -0.2], [0.1, 7.0, -0.3], [0.3, -0.2, 10.0]]
b = [[7.85], [19.3], [71.4]]
GaussNaive(A, b)

U= [[ 3.         -0.1        -0.2         7.85      ]
 [ 0.          7.00333333 -0.29333333 19.03833333]
 [ 0.          0.         10.01204188 71.13150881]]
x= [[ 7.85      ]
 [19.03833333]
 [71.13150881]]
